name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile.production -t ${{ secrets.DOCKERHUB_USERNAME }}/29:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/29:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: "${{ secrets.HOST }}"
          username: "${{ secrets.USERNAME }}"
          key: "${{ secrets.SECRET_PRIVATE_KEY }}"
          port: "${{ secrets.PORT }}"
          script: |
            cd /var/ci_cd
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/29:latest
            cd 29
            echo "Stoping and removing old version..."
            docker stop 29 && docker rm 29
            docker run --restart=always --name 29 -p 5000:80 -d ${{ secrets.DOCKERHUB_USERNAME }}/29:latest
